# Instalar y conectar Git, GitHub y RStudio {#instalacion}

**Traducción de la información principal del capítulo 4 "Register a GitHub account", capítulo 5 "Install or upgrade R and RStudio", capítulo 6 "Install Git" y capítulo 7 "Introduce yourself to Git" del libro de "Happy Git with R" de Jenny Bryan**

## Crear una cuenta en GitHub

Crear una cuenta en GitHub es gratis y puedes hacerlo en la siguiente página web: [https://github.com](https://github.com)

**Nombre (Username)**

Para hacer tu cuenta necesitarás escoger un nombre (username), para lo cual Jenny Bryan recomienda considerar: 
  
  - ¡Usa tu nombre! Así es más fácil de recordar y encontrarte. 
  
  - Re-usa el nombre de otros medios sociales cómo Twitter o Slack.
  
  - Considera sentirte cómoda/o con el nombre (username), cómo para en un futuro mostrárselo a tu jefa/e. 
  
  - Un nombre corto es mejor que algo muy extenso. 
  
  - Haz que sea lo más único posible.
  
  - Que no sea determinado por un periodo de tu vida. No uses tu universidad, trabajo o residencia, por ejemplo. 
  - Evita nombres que contengan palabras usadas normalmente en programación (como `NA`, que puede significar missing values). 
  
  - No uses letras mayúsculas para separar entre palabras. Si puedes, que todo tu nombre tenga solo minusculas y si quieres separar palabras, mejor usar los símbolos "_" o "-".  

Puedes modificar el nombre (username) más tarde, pero es más fácil si lo haces bien a la primera. Si quisieras cambiarlo revisa estas páginas web: 

  - https://help.github.com/articles/changing-your-github-username/
  
  - https://help.github.com/articles/what-happens-when-i-change-my-username/

**Uso de repositorios gratuitos privados**

GitHub te ofrece la opción ilimitada de repositorios privados para todos sus usuarios. Estos pueden soportar hasta tres colaboradores externos lo que lo hace perfecto para tus proyectos personales, entre otros. 

Para el caso de estudiantes y personal en las áreas de investigación y educación, para ello revisa: [https://education.github.com](https://education.github.com)

Para organizaciones sin fines de lucro y fundaciones, revisa: [https://github.com/nonprofit](https://github.com/nonprofit)

**Pagar por repositorios privados**

Cualquiera puede pagar por tener repositorios privados que soportan un número ilimitado de colaboradores. Esto no necesitas hacerlo ahora ya que puedes en el futuro decidir comenzar a pagarlo. Más información [https://github.com/pricing](https://github.com/pricing)

## Instalar (o actualizar) R y RStudio 

  1. Para instalar R, lo puedes hacer en el siguiente enlace: [https://cloud.r-project.org](https://cloud.r-project.org)
  
  Si ya lo tienes instalado, quizás este es el momento perfecto para actualizarlo. Si quieres revisar qué versión estás usando, hazlo con:
  
```{}
R.version.string
#> [1] "R version 4.0.0 (2020-04-24)"
```

  2. Instala RStudio, y si ya lo tienes, quizás es el momento ideal también para actualizarlo. Descárgalo aquí: [https://www.rstudio.com/products/rstudio/download/preview/](https://www.rstudio.com/products/rstudio/download/preview/)

  3. Para actualizar los paquetes de R:
  
```{}
update.packages(ask = FALSE, checkBuilt = TRUE)
```

## Instala Git

Para usar Git en la línea de comando y con RStudio, necesitas:

1 .- Instalarlo. 
2.- Revisar si ya lo tienes instalado, si fuera así no necesitas seguir estos pasos.
3.- Si no, a continuación están las formas de instalarlo según tu sistema operativo. 

Para saber si ya lo tienes instalado en tu computador, abre la terminal de tu computador e ingresa "which git": 

```{}
which git 
## /usr/bin/git
```  

Luego "git --version", para saber que versión tienes: 

```{}
git --version
## git version 2.21.0
```

Si ves que a los comandos ingresados, obtienes cómo respuesta `git: command not found`, entonces considera instalar Git con los pasos que se describen más abajo. 

A los usuarios de macOS, suele mostrarles una oferta intermediaria para instalar las líneas de comando de estas herramientas. En esos casos, deberás aceptar,  hacer click en "Instalar" y revisar los pasos que se detallan más abajo.

**I. Instalar Git en Windows**

Hay tres opciones: 

**Opción 1 (¡altamente recomendado!):** Instala Git para Windows a través de esta web: [https://gitforwindows.org](https://gitforwindows.org). También es conocido como "msysgit" o "Git Bash" el cual instala también una consola ("bash shell") y algunas otras herramientas útiles. 

Esta es buena opción, porque Git para Windows deja el ejecutable en una ubicación convencional lo que te ayudará a encontrarlo y usarlo. Esto también admite una transición a un uso más experto, especialmente cuando tengas que trabajar fuera de RStudio.

  - ¡OJO! considera que cuando te pregunte "Adjusting your PATH environment", selecciona "Git from the command line and also from 3rd-party software". Si no, siempre es bueno aceptar lo que viene por defecto.
  
  - Considera que RStudio para Windows prefiere que instales Git dentro de "C:/Program/Files", ruta que debe estar por defecto. Esto significa que, por ejemplo, Git estará en tu Windows en: "C:/Program/Files/Git/bin/git.exe". 

**Opción 2:** Instala Git para [Windows](https://gitforwindows.org) desde el paquete ["chocolatey"](https://chocolatey.org). 

Entonces primero instala chocolatey en tu computador, luego agrega en tu terminal:

```{}
choco install git.install
```

**II. Instalar Git en macOS**

Hay tres opciones también:

**Opción 1 (¡altamente recomendado!):** Instalar el comando  Xcode (desde la línea de comando), el que viene viene con Git. Para hacer eso, tienes que ir a la terminal y agregar uno de los siguientes comandos para ver las ofertas de instalación del desarrollador:

```{}
git --version
git config
```

Luego, ¡acepta la oferta! haciendo click en "Install". O puedes pedir de forma directa la instalación con el siguiente comando:

```{}
xcode-select --install
````

Considera que quizás tendrás que re-hacer este proceso, si es que actualizas tu sistema macOS. 

**Opción 2:** Instalarlo directo de la siguiente página web: [http://git-scm.com/downloads](http://git-scm.com/downloads)

  - Esta opción te entregará el beneficio de que te dará la última versión disponible de Git.
  
  - Más información sobre GitHub home para macOS, puede ser encontrada [aquí](https://github.com/timcharper/git_osx_installer)
 
**Opción 3:** Si anticipas que estarás trabajando con procesos computacionales altamente demandantes, estarás entonces instalando y actualizando muchos programas. Revisa entonces el "missins package manager for OS X" en la siguiente página web:  [https://brew.sh](https://brew.sh) Una vez que lo tengas instalado, agrega en el terminal el siguiente comando para instalar Git:
  
```{}
brew install git
```

**III. Instalar Git en Linux**

Instala Git a través del administrador de paquetes de tu distribución (distro's package manager):

Ubuntu o Debian Linux:

```{}
sudo apt-get install git
````

Fedora o RedHat Linux:

```{}
sudo yum install git
```

Una lista completa para varios administradores de paquetes (package managers) de Linux y Unix la encuentras [aquí](https://git-scm.com/download/linux)

## Preséntate a Git 

En la terminal de tu computador agrega: 

```{}
git config --global user.name 'Jane Doe'
git config --global user.email 'jane@example.com'
git config --global --list
```

Sustituye con tu nombre y el correo asociado a tu cuenta de GitHub. Otra opción es usar el paquete de R "usethis", que te permite hacerlo en solo una línea:

```{}
## install.packages("usethis")

library(usethis)
use_git_config(user.name = "Jane Doe", user.email = "jane@example.org")
```

**Más sobre la configuración de Git**

Otra forma de acceder al terminal es desde RStudio, apretar en "Tools", y después hacer click en "Terminal" (o a veces dice "Shell").

Considera que si estás usando Windows, a veces eso puede traer problemas con el terminal que estás usando ya que Windows poseen varios. Dado esto, asegúrate de que estás usando la terminal "Git Bash". Esto puede ser más fácil de resolver si realizas la configuración de Git usando el paquete de R `usethis`. 

El nombre de usuario usado en Git no debe ser necesariamente el mismo de tu cuenta de GitHub. Aunque si quieres, puede ser así. Otra buena opción es tu nombre y tu apellido. Si es que haces commit desde distintas maquinas, a veces la gente usa esa información como el nombre de usuario. Los commits tendrán este nombre, por lo que asegúrate de que sea informativo para futuras posibles colaboraciones. 

Es importante considerar que el correo que usas para Git **TIENE QUE SER EL MISMO DE TU CUENTA GitHub**. 

Si estos comandos no te entregan ninguna respuesta, puedes revisar si Git entendió lo que necesitabas, escribiendo `git config --global --list`.

**Configura el editor de Git**

Otra opción de Git que muchas personas eventualmente configuran es el editor. En algún momento, no le darás a Git lo que requiere en los commits y te enviará a un editor. Esto puede ser angustiante si no es el editor de tu elección y ni siquiera sabes cómo guardar y salir de él. 

Puedes forzar el que necesitas escribiendo algo como esto:

```{}
git config --global core.editor "emacs"
```

Sustituye tu editor por "emacs" allí. 

En la siguiente [página web](http://swcarpentry.github.io/git-novice/02-setup/) puedes encontrar una lista completa de los comandos exactos usados por `git config`, que pueden ser útiles para muchas combinaciones entre el Sistema Operativo y el editor.
